### ISSUE TITLE
Getting an error while building: "env: unbuffer: No such file or directory"

### ISSUE THREAD

**Issue by abchk1234** [idlemoor/slackrepo#1]
This is from the log file:

```
Starting desktop/screenfetch (add version 3.6.5) 2015-01-08 10:41:14
Verifying source files ...
Running screenfetch.SlackBuild ...
env MAKEFLAGS='-j3'  unbuffer sh ./screenfetch.SlackBuild
env: unbuffer: No such file or directory
ERROR: desktop/screenfetch: screenfetch.SlackBuild failed (status 127)
```

I dont know why it is passing unbuffer while building, I dont think I have specified it anywhere.
I will look at my configs though to see if I missed anything :)
Using git version of the package.

This is the complete output: http://paste2.org/xEEFWBD0
And my config file is as follows:

```
# cat ~/.slackreporc
# Config file for slackrepo
REPO=SBo
SBREPO=/mnt/datalinux/git/slackbuilds
PKGREPO=/home/aaditya/packages
SRCREPO=/home/aaditya/src
HINTDIR=/home/aaditya/slackrepo/hintfiles
LOGDIR=/home/aaditya/slackrepo/logs
QUEUEDIR="/home/aaditya/slackrepo/queuefiles"
TMP=/tmp
NUMJOBS='-j3'
TAG='_SBo'
PKGTYPE='tgz'
verbose='y'
VERY_VERBOSE='n'
KEEP_TMP='y'
MAKE_VERBOSE='y'
TEST='y'
```

_Edit-_
Downgrading to version 0.1.2 provided on the website seems to work.

```
Starting desktop/screenfetch (add version 3.6.5) ------------------------------
Testing SlackBuild files ...
Verifying source files ...
Testing download URLs ...
Running screenfetch.SlackBuild ...
Testing screenfetch-3.6.5-noarch-1_SBo.tgz...
:-) desktop/screenfetch: Added version 3.6.5 (screenfetch: The Bash Screenshot Information Tool) (-:
```

**Comment by idlemoor** [comment]
Hi Aaditya,

It's a new feature that isn't documented yet :-) it will use 'unbuffer' to trick cmake, clang and (eventually) gcc-4.9 into producing colour output. unbuffer is in Slackware's 'expect' package, but because it is a really obscure dependency, I will add a test to only use unbuffer if it is available. Hopefully I will be able to fix this later today, meanwhile you can disable colour output with the argument '--colour=never'. Sorry for the surprise and thank you for the report!

**Comment by abchk1234** [comment]
Hi David,

Thx for your response :)
I will disable the color output or install the expect package.

One thing you might want to mention in your tutorials is that slackrepo could install and uninstall stuff on its own, for example when I had the _test_ option enabled, it uninstalled some of my previously installed programs.

Similarly for building, it installs/uninstalls without asking, for example I had ffmpeg from AlienBob installed, but while building aegisub it removed that.

This was with the 0.1.2 version, I will try out with the git version to see if that behaviour still there.
I guess it maybe aligned with one of the goals though, of non-interactive building :)

**Comment by abchk1234** [comment]
After installing the expect package it works again.
I will open another bug about the removal issue with test option.
