### ISSUE TITLE
circular dependencys

### ISSUE THREAD

**Issue by rbns** [idlemoor/slackrepo#10]
for example: ffmpeg has the optional depencency opencv (enabled by custom hintfile), opencv has the optional dependency ffmpeg (enabled in the default hintfile).
when trying to build ffmpeg then, slackrepo loops while building the dependency tree. when removing opencv from the ffmpeg hintfile, all works as usual.

**Comment by idlemoor** [comment]
Well it's almost happy second birthday for this issue, but I finally fixed it recently in 3fa97b7616114aa0f2667c89f46292ffa609822e

If you're still around @rbns thanks very much indeed!

**Comment by rbns** [comment]
happy to help! :)
