### ISSUE TITLE
slackrepo sporadically fails on 14.2

### ISSUE THREAD

**Issue by rbns** [idlemoor/slackrepo#13]
after upgrading to 14.2 slackrepo fails.
the output is:

```
Starting system/mksh (add version R52) 2016-07-03 23:49:56
Verifying source files ...
Running mksh.SlackBuild ...                                         ETA 23:51:??
env MAKEFLAGS='-j5' /usr/libexec/slackrepo/unbuffer nice -n 5 sh ./mksh.SlackBuild
sh: line 0: cd: /tmp/slackrepo.gqReaQ/slackbuild_mksh: No such file or directory
sh: ./mksh.SlackBuild: No such file or directory
system/mksh: mksh.SlackBuild failed (status 127)                        23:49:56
Unmounting chroot ...
:-( system/mksh FAILED )-:
```

After changing the mount of /tmp back from tmpf to a "normal" file system it worked for some time, then failed again. I'll investigate a bit further.

**Comment by rbns** [comment]
I guess there are some problems with the fakeroot stuff now, running as root works. as user i the error
`The system has no more ptys.  Ask your system administrator to create more.` from /usr/libexec/slackrepo/unbuffer around line 16.

I'll add another output when I've got the time.

**Comment by idlemoor** [comment]
This caused me a lot of pain too -- You were right that the 'ptys' error message was part of the same problem with temp files and fakeroot. It has taken at least five separate commits to finally get this (hopefully) right, 7c6e9fc27be853a5ca6b9c2675e3fa05f770fc2c e62ef97d70f98e0ff62fddb6d9204bd8d41c94f9  c5eb6e5e23cbfc5652f51f023aa5504f0be5ce8f f8baf2983400de6e6ca7e1c8faace044cec7f2db and a49a959192578d886e2e6bc4a34c3e456c5351a4

Thanks for the report :D
