### ISSUE TITLE
ERROR: install_packages cannot find item

### ISSUE THREAD

**Issue by ghost** [idlemoor/slackrepo#14]
I am trying to build, install and test on the same machine.  In function [install_packages](https://github.com/idlemoor/slackrepo/blob/master/libexec/functions.d/installfunctions.sh#L63) there seems to be a problem locating packages in /tmp.  I reproduced this with three slackbuilds: pyperclip, xfce4-wavelan-plugin, and pyPdf.

Let me know if you need more information.  Thanks!

Example

> root@darkstar[~]# slackrepo rebuild --install pyperclip
> Cleaning /tmp/SBo ... done.
> Checking whether git is clean ... yes.
> git repo: /var/lib/slackrepo/SBo/slackbuilds
> branch:   14.2
> date:     Sat Jul  2 08:28:09 MDT 2016
> revision: 2c2c27d6bcc6c83a0a7f493d2bb0511d23134810
> title:    Public www update: Sat Jul  2 14:27:42 UTC 2016.
> # 
> 
> python/pyperclip                                                        00:59:46
>  ==============================================================================
> 
> Calculating dependencies ... none.
> 
> Starting python/pyperclip (rebuild) [install] ------------------------- 00:59:46
> Verifying source files ... done.
> Running pyperclip.SlackBuild ...                                    ETA 01:00:??
> env MAKEFLAGS='-j5' nice -n 5 sh ./pyperclip.SlackBuild
> Built ok:  pyperclip-1.5.25-i486-2_SBo.tgz                              00:59:47
> Unmounting chroot ... done.
> ERROR: install_packages cannot find item /tmp/slackrepo.xrplYI/chroot//tmp/slackrepo.xrplYI/packages_pyperclip/pyperclip-1.5.25-i486-2_SBo.tgz
> See /var/log/slackrepo/SBo/python/pyperclip/rebuild.log
> :-( python/pyperclip FAILED )-:
> 
>  =============================================================================
> SUMMARY                                                                 00:59:47
> 
>  ====================================================================
> 
> Logfile:     /var/log/slackrepo/SBo/slackrepo_2016-07-06_00:59:46.log
> Runtime:     0h 0m 1s
> Failed:      1
>   python/pyperclip
> `

**Comment by ghost** [comment]
It looks like if I edit my configuration (/etc/slackrepo/slackrepo_SBo.conf) and set: 

> CHROOT='n'

This problem goes away.

The chroot_destroy function removes the package and install_packages cannot find it.  I am not much of a programmer so it's unlikely I will be able to provide a patch.  It seems like the ordering of things needs to change so that the control arg "--install" activates install_packages in a different place.

**Comment by idlemoor** [comment]
Hi Brenton, finally I think this is fixed -- it took a significant rewrite 8263366e4957aa24b26282c68c91bd22be9dda49 and a fix for a really stupid bug 12797f742ed14408375a9a53515544b88d6cd86b but I think it is in better shape now

Thanks for the report :)
