### ISSUE TITLE
Separate hinfiles from slackrepo

### ISSUE THREAD

**Issue by atelszewski** [idlemoor/slackrepo#15]
Hi,

This is just a suggestion.
Maybe you could split slackrepo and have separate slackrepo-hinfile package?
You could then just update hintfiles and release them, without issuing another releases of slackrepo.

Well, I don't use your hintfiles, so that's the main reason for this suggestion ;-)

--
Best regards,
Andrzej Telszewski

**Comment by idlemoor** [comment]
Hi Andrzej,

I thought about this for a long time, and.... 

...

...

...

you are 100% right, so I did it yesterday, and you are still 100% right today, so I'll close this when it looks like nothing is broken :D
Thanks!

**Comment by idlemoor** [comment]
Yep, this is working well -- thanks very much indeed for a great suggestion!
