### ISSUE TITLE
Bad permissions on sudoers.d

### ISSUE THREAD

**Issue by atelszewski** [idlemoor/slackrepo#16]
Hi,

The provided SlackBuild creates package which causes /etc/sudoers.d and /etc/sudoers.d/* to have wrong permissions.

'Others' should not have any of the read/write/execute bit set.
Only the 'owner' should have read/write/execute and the 'group' read/execute bits set (execute for directories only of course).

I would suggest to use 'install' with appropriate permissions in the SlackBuild, instead of plain old & good cp ;-)

--
Best regards,
Andrzej Telszewski

**Comment by idlemoor** [comment]
Sorry to have taken so long to say Thank You for this -- it was fixed in a3a508590112d9db98182fe899ae19cf374638a8 :)
