### ISSUE TITLE
Custom .SlackBuilds

### ISSUE THREAD

**Issue by dagmoller** [idlemoor/slackrepo#19]
There is a way to use modified .SlackBuild files? like sbopkg does?

**Comment by idlemoor** [comment]
Hi! You can create your own branch in the git repository and commit your changes. Then you can keep your branch up-to-date with SBo by rebasing your branch on SBo's master branch. 

(Or if you just want to build a newer version, you can create a hint with VERSION='x.y.z' so you don't have to modify the SlackBuild.)

**Comment by dagmoller** [comment]
Thanks...

**Comment by dagmoller** [comment]
Sometimes rebasing is painfull
