### ISSUE TITLE
update download instructions please

### ISSUE THREAD

**Issue by mdeanda** [idlemoor/slackrepo#6]
if you have it use the https git url it works better for people not logged in.

**Comment by idlemoor** [comment]
That's very helpful Miguel, thank you! I'll try to do that tonight :-)

**Comment by idlemoor** [comment]
Ok, on the Download page, the Git snapshot paragraph now says 'git clone https://...'
I hope I've not missed any more instances!
Thanks once again Miguel, I might never have caught that myself.
