### ISSUE TITLE
Fail to build vid.stab

### ISSUE THREAD

**Issue by alikve** [idlemoor/slackrepo#8]
The command
`# slackrepo build vid.stab`
results in

```
:-( BAD ARGUMENT 'vid.stab' )-:
No matches found for build command
```

The SlackBuild "vid.stab exists ": http://slackbuilds.org/repository/14.1/libraries/vid.stab/

Maybe the dot in the name confuses `slackrepo`?

I use version `gitf05cadd`.

**Comment by alikve** [comment]
Answering my own question, the dot must be escaped:
`# slackrepo build vid\.stab`

Also, this package requires
`PRAGMA="download_basename"`

**Comment by alikve** [comment]
I'd like to add that to put `vid.stab` to the ADDREQUIRES variable in a hint file one should use single quotes `ADDREQUIRES=' ... vid.stab ...'`

**Comment by idlemoor** [comment]
Hi slalik, sorry about the delay in answering...

I'm rewriting the code that parses command arguments (my old code is rubbish, to be honest) so I will try to fix this problem when I merge the new code. Thanks for pointing it out, it's much appreciated!

**Comment by alikve** [comment]
Hello **idlemoor**, I wanted to say thank you for your genius program!!
I'm migrating my computers from debian and slackrepo is my best friend.
Still, I have a request, if possible, could you consider to change the yellow color of warning messages to any color visible on a white background?

**Comment by idlemoor** [comment]
Thanks! That's a great suggestion, I'll use magenta (the same colour as gcc-4.9), and it should be easy to make it configurable like GCC_COLORS and LS_COLORS. I'll try to do that later this week. Thanks again!
