### ISSUE TITLE
openrc

### ISSUE THREAD

**Issue by slackpanos** [idlemoor/slackrepo#9]
openrc is a dependency for openrc-services, after installed removes inittab. 
How can i tell slackrepo in hintfile to make a backup to inittab (cp /etc/inittab /etc/inittab.bak)?
and then restore back with this:
CLEANUP="mv /etc/inittab.bak /etc/inittab"

**Comment by idlemoor** [comment]
Oh Shit! Yes I see the problem -- sorry for the disaster!  And sorry about the delay in answering!

I think maybe the best solution will be if I make the cleanup code more gentle, like removepkg, then there won't be any more disasters like this in future. I'll try to find a solution as soon as possible.

(This makes me understand how carefully designed removepkg is...)
